feat: able to add extra envs to UI container
eshepelyuk/cmak-operator pull request #41
Opened 2021-12-08 18:25 UTC by caiofralmeida

Able to add extra envs to UI container configuration through values files.

related to the issue https://github.com/eshepelyuk/cmak-operator/issues/40

2021-12-08 18:36 UTC, eshepelyuk requested changes
1. As soon as you change / add values - you should adjust values schema. Also it will be great if you can add corresponding linter tests, check `test/linter` folder.
2. Also, since you changed templates - please add helm unit tests , under `test/unit` folder.
3. Plz name new values as `extraEnv` - it is more wide spread in helm charts, so more common.

2021-12-08 18:37 UTC, eshepelyuk requested changes
please refer to contributing page regarding the format of commit messages.

2021-12-08 18:42 UTC, eshepelyuk requested changes
The most important change is theformat of new values variable. It should not be just an object of values that are transformed into name / value pairs.
Instead int must be a **list** of objects, where each object is reflecting a one of the possible format of declaring pod env vars according to k8s doc, i.e. name/value, env from configmap, anv from secret etc.

2021-12-08 18:46 UTC, eshepelyuk commented on templates/deployment.yaml
> +          {{- if or .Values.ui.consumerProperties .Values.ui.extraEnvs }}
Plz move `env` outside of any if condition, i.e. make it render always.

2021-12-08 18:48 UTC, eshepelyuk reviewed
Also I would be very appreciated if you can modify the readme, by adding an alternative approach to configure basic auth via secret and env vars, 

https://github.com/eshepelyuk/cmak-operator#cmak-application-settings

2021-12-09 13:39 UTC, caiofralmeida commented
@eshepelyuk thanks for the review and feedback, I'm going to fix it.

2021-12-30 18:47 UTC, eshepelyuk commented
Hello @caiofralmeida 
What are yout interntions about this PR ?

2021-12-30 18:58 UTC, caiofralmeida commented
@eshepelyuk Sorry for late, I'm out of work until 17th January. Maybe we can close this PR for now, and when I back, I can reopen with all requested changes.

2021-12-30 20:20 UTC, eshepelyuk commented
Thanks for reply @caiofralmeida 
I just wanted to make sure that this PR is not abandoned.
So, as soon as you have time - let's proceed and finalize it.

2022-01-19 14:29 UTC, caiofralmeida commented
Hi @eshepelyuk, is there a way to run unit tests locally?

2022-01-19 15:10 UTC, eshepelyuk requested changes
1. don't use existing unit test for a new test case, create a new file instead
1. the new test should have 2 cases
    - when extra env values are passed ( one you've provided)
    - when no extra env passed (default behaviour) 
1. your schema is  incorrect
    - default value must be empty list / array `[]`, not empty object `{}`
    - you should declare types of items in `extraEnv` array, in this case just use `object`
    - that also should be covered by linter tests

2022-01-19 21:36 UTC, eshepelyuk commented
@caiofralmeida jFYI - I've updated `CONTRIBUTING` page, hopefully it became more useful.

2022-01-21 21:24 UTC, eshepelyuk commented
Superseeded by #46

2022-01-21 21:24 UTC, closed without merging